#!/bin/bash
set -Eeo pipefail

dotnet_publish_output="Backend/app/publish"

command="$1"
case "${command}" in 
  _build)
    if [[ -d ${dotnet_publish_output} ]]; then rm -r ${dotnet_publish_output}; fi

      operating_system="win-x64"
      if [[ "$OSTYPE" == "linux-gnu"* ]]; then
          operating_system="linux-x64"
      fi
      set -x; dotnet publish -c Release -r "${operating_system}" --self-contained false -o ${dotnet_publish_output} Backend/TodoList.Api/TodoList.Api.sln
      ;;
  build)
    docker run --rm -v ${PWD}:/tmp/work mcr.microsoft.com/dotnet/sdk:6.0 bash -c "cd /tmp/work && ./tasks _build"
    ;;
  _unit)
    dotnet test -c Debug -v minimal Backend/TodoList.Api/TodoList.Api.UnitTests/
    ;;
  unit)
    docker run --rm -v ${PWD}:/tmp/work mcr.microsoft.com/dotnet/sdk:6.0 bash -c "cd /tmp/work && ./tasks _unit"
    ;;
  esac