name: Main

on:
  push:
    branches:
      - "*"
      # ignore all tags https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#example-excluding-branches-and-tags
    tags-ignore:
      - "*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Running bash script
        run: ./tasks build
  unit:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - uses: actions/checkout@v3
      - run: ./tasks unit
  docker:
    needs: [build, unit]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: ./tasks build_docker
      - name: Extract branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch
      - uses: actions/upload-artifact@v3
        with:
          name: imagerc-${{ steps.extract_branch.outputs.branch }}-${{ github.sha }}-${{ github.run_number }}-${{ github.run_attempt }}-${{ github.workflow }}
          path: Backend/TodoList.Api/imagerc.yml
          retention-days: 5
      - run: ./tasks e2e
